image: registry.gitlab.com/pages/hugo:latest

workflow:
  rules:
    - if: '$CT_COMMIT_BRANCH'

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master

pages:
  script:
    - hugo
  artifacts:
    paths:
    - public
  rules:
    - if: '$CT_COMMIT_BRANCH == "gl-pages"'
